In [4]:
import numpy as np

# random output Vector
a = np.random.randn(5)
print (a)

[ 0.64497992 -0.68066398 -0.77273038  0.13984243 -1.37449654]


In [7]:
expa  = np.exp(a)
print (expa)

[1.90594876 0.50628072 0.46175059 1.15009256 0.25296692]


In [9]:
answer = expa / expa.sum()
print (answer)

[0.44562337 0.11837176 0.10796033 0.26889921 0.05914533]


In [11]:
answer.sum()

1.0

In [13]:
# Random output Matrix A

A = np.random.randn(100, 5)
print(A)

[[ 0.42329024  1.58862264  0.43999696 -0.97347873  0.43050844]
 [ 0.76894383  2.5057307  -0.33610255 -1.89600118  0.05456103]
 [ 0.05067017  0.31862943 -0.30237259  0.04037756 -2.15375036]
 [-0.37542759 -1.00087632  1.12563424 -0.70438969 -1.13397615]
 [ 1.22861884 -0.38418504 -0.56458698 -0.17946904  0.10609876]
 [ 0.06423124 -0.88760922  0.23205116  0.2738941  -0.84054781]
 [-0.62169986  0.11913771  0.23943788 -0.19276351 -0.37660469]
 [ 2.70864371 -1.77721452  0.45846097  1.09369535  2.44235862]
 [-1.28619383 -1.96649075 -1.09001253  1.23913642  0.00644223]
 [-0.84302064  1.10922408  0.86920092 -2.14544177 -0.91902839]
 [-0.68587252 -1.18373454  0.59563085 -0.95460518  1.3484723 ]
 [-0.93544946 -0.32897111 -0.66882458  1.59473203 -0.70526353]
 [-0.30390631 -2.00646772 -0.31429775 -1.36069154 -0.30127228]
 [ 1.48647433  0.13262232 -0.20351136  0.35299158  0.69502976]
 [ 0.672678   -0.7273767   0.4975357  -0.22377858  0.08786888]
 [-0.15796806  1.86268397  0.08524832 -2.02495683  1.75

In [15]:
expA = np.exp(A)
print(expA)

[[ 1.52697742  4.89699936  1.55270249  0.3777666   1.53803933]
 [ 2.15748638 12.25250864  0.71454983  0.15016791  1.05607692]
 [ 1.05197586  1.37524161  0.73906264  1.04120381  0.11604812]
 [ 0.68699546  0.3675572   3.08217107  0.49441023  0.32175138]
 [ 3.41650755  0.6810054   0.56859494  0.83571382  1.11193169]
 [ 1.06633895  0.41163872  1.26118425  1.31507552  0.43147409]
 [ 0.53703079  1.12652504  1.27053476  0.82467698  0.68618728]
 [15.00890535  0.16910854  1.58163792  2.98528538 11.50013322]
 [ 0.27632051  0.1399471   0.33621228  3.45263055  1.00646303]
 [ 0.43040845  3.0320049   2.38500428  0.11701633  0.39890643]
 [ 0.50365059  0.30613333  1.81417505  0.38496411  3.85153703]
 [ 0.39240945  0.71966381  0.5123104   4.92700861  0.49397838]
 [ 0.73793     0.1344628   0.73030155  0.25648335  0.73987629]
 [ 4.42147931  1.14181867  0.81586093  1.42331915  2.00376871]
 [ 1.95947779  0.48317484  1.64466334  0.79949214  1.09184495]
 [ 0.85387705  6.44100104  1.08898745  0.13199954  5.76

In [18]:
answer  = expA / expA.sum(axis = 1, keepdims = True)
print(answer)

[[0.15435731 0.49502216 0.15695778 0.03818723 0.15547553]
 [0.13211158 0.75027043 0.04375476 0.00919539 0.06466784]
 [0.243314   0.3180829  0.17093955 0.2408225  0.02684104]
 [0.13870611 0.07421072 0.62229809 0.09982267 0.06496241]
 [0.51657619 0.10296807 0.0859716  0.12635999 0.16812415]
 [0.23771902 0.09176665 0.2811559  0.29316988 0.09618855]
 [0.12081805 0.25343903 0.2858375  0.18553101 0.15437441]
 [0.48036075 0.00541233 0.0506204  0.0955442  0.36806232]
 [0.05302055 0.02685314 0.06451262 0.66249292 0.19312076]
 [0.06763876 0.47648007 0.37480382 0.01838914 0.06268821]
 [0.07341353 0.04462286 0.26443927 0.05611345 0.56141089]
 [0.05569749 0.10214705 0.07271589 0.69932568 0.0701139 ]
 [0.28392254 0.05173528 0.28098745 0.09868335 0.28467138]
 [0.45088395 0.11643789 0.08319808 0.14514413 0.20433595]
 [0.32774569 0.08081667 0.27508928 0.13372446 0.1826239 ]
 [0.05978288 0.45095672 0.07624377 0.00924174 0.40377489]
 [0.01381972 0.00999158 0.15639343 0.23351334 0.58628193]
 [0.28964382 0

In [21]:
answer.sum(axis=1, dtype = float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])